#!/bin/sh

# Xcode Cloud runs this immediately after cloning the repo, before resolving
# dependencies and before xcodebuild. The .xcodeproj is generated by XcodeGen
# (project.yml is the source of truth; the project is gitignored), so it does
# not exist in a fresh clone — regenerate it here or the build can't find it.

set -e

# Honor the XcodeGen version pinned in the Mintfile so CI matches local dev.
echo "Installing Mint…"
export HOMEBREW_NO_INSTALL_CLEANUP=1
brew install mint

# Xcode Cloud clones into $CI_PRIMARY_REPOSITORY_PATH (the repo root).
cd "$CI_PRIMARY_REPOSITORY_PATH"

echo "Generating gameday.xcodeproj with XcodeGen…"
mint bootstrap            # installs the pinned XcodeGen from the Mintfile
mint run xcodegen generate

echo "Done. Generated:"
ls -d gameday.xcodeproj
